{% set version = '1.10.16' %}
{% set sha256 = '7d9a43bf46054275db3aa61c0ca6dfa25202d11e3c2b061ce6e67586e8d785fa' %}

package:
  name: ant
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/ant/source/apache-ant-{{ version }}-src.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # no openjdk available for those platforms
  skip: true  # [ppc64le or s390x]

requirements:
  build:
    - openjdk >=8
  run:
    - openjdk >=8

test:
  commands:
    - chmod +x $PREFIX/bin/j*  # [osx]
    - ant -help
    - ant -version

about:
  home: https://ant.apache.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Apache Ant is a Java library and command-line tool that mainly helps building software.
  description: |
    Apache Ant is a Java library and command-line tool whose mission is to
    drive processes described in build files as targets and extension points
    dependent upon each other. The main known usage of Ant is the build of
    Java applications.
  dev_url: https://github.com/apache/ant
  doc_url: https://ant.apache.org/manual/index.html
