{% set version = '1.10.17' %}
{% set sha256 = '0acd8eb8c3ea9505bcd422baad746aad62c2f8f691cc872e2046e283e85217c0' %}

package:
  name: ant
  version: {{ version }}

source:
  url: https://archive.apache.org/dist/ant/source/apache-ant-{{ version }}-src.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
requirements:
  build:
    - openjdk >=8
  run:
    - openjdk >=8

test:
  commands:
    - chmod +x $PREFIX/bin/j*  # [osx]
    - ant -h

about:
  home: http://ant.apache.org/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Java build tool'
  description: |
    Apache Ant is a Java library and command-line tool whose mission is to
    drive processes described in build files as targets and extension points
    dependent upon each other. The main known usage of Ant is the build of
    Java applications.
  dev_url: https://git-wip-us.apache.org/repos/asf?p=ant.git;a=summary
  doc_url: http://ant.apache.org/manual/index.html
